-- +goose Up
-- +goose StatementBegin

-- Magic-link auth has been replaced with admin password + invite codes +
-- long-lived device tokens. Drop the now-unused tables.
DROP TABLE IF EXISTS magic_tokens;
DROP TABLE IF EXISTS refresh_tokens;

-- Admin password hash (nullable — non-admin users auth via device tokens).
ALTER TABLE users ADD COLUMN password_hash TEXT;

-- Single-use invite codes generated by the admin.
CREATE TABLE invite_codes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code_hash VARCHAR(255) NOT NULL UNIQUE,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    note VARCHAR(255),
    redeemed_by UUID REFERENCES users(id) ON DELETE SET NULL,
    redeemed_at TIMESTAMP,
    expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_invite_codes_hash ON invite_codes(code_hash);

-- Long-lived device tokens: one per user (one user = one device).
CREATE TABLE device_tokens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    device_label VARCHAR(128),
    last_seen_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_device_tokens_hash ON device_tokens(token_hash);

-- One-time bootstrap token: persisted so it survives restarts until consumed.
CREATE TABLE setup_tokens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    used_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS setup_tokens;
DROP TABLE IF EXISTS device_tokens;
DROP TABLE IF EXISTS invite_codes;
ALTER TABLE users DROP COLUMN IF EXISTS password_hash;

-- Recreate the magic-link tables so Down leaves the schema rollback-compatible.
CREATE TABLE magic_tokens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX idx_magic_tokens_user_id ON magic_tokens(user_id);
CREATE INDEX idx_magic_tokens_expires ON magic_tokens(expires_at);

CREATE TABLE refresh_tokens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens(expires_at);
-- +goose StatementEnd
