// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupServe(arg1) {
  return window['go']['main']['App']['CleanupServe'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function ExtractThumbnail(arg1, arg2) {
  return window['go']['main']['App']['ExtractThumbnail'](arg1, arg2);
}

export function FFmpegIsAvailable() {
  return window['go']['main']['App']['FFmpegIsAvailable']();
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetAuthToken() {
  return window['go']['main']['App']['GetAuthToken']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFileSize(arg1) {
  return window['go']['main']['App']['GetFileSize'](arg1);
}

export function GetMediaServerURL() {
  return window['go']['main']['App']['GetMediaServerURL']();
}

export function HandleAuthCallback(arg1) {
  return window['go']['main']['App']['HandleAuthCallback'](arg1);
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function LoginAdmin(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginAdmin'](arg1, arg2, arg3);
}

export function LogoutDevice() {
  return window['go']['main']['App']['LogoutDevice']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ProbeServer(arg1) {
  return window['go']['main']['App']['ProbeServer'](arg1);
}

export function ProbeVideo(arg1) {
  return window['go']['main']['App']['ProbeVideo'](arg1);
}

export function ProxyVideoURL(arg1, arg2) {
  return window['go']['main']['App']['ProxyVideoURL'](arg1, arg2);
}

export function RedeemInvite(arg1, arg2, arg3) {
  return window['go']['main']['App']['RedeemInvite'](arg1, arg2, arg3);
}

export function ServeLocalFile(arg1) {
  return window['go']['main']['App']['ServeLocalFile'](arg1);
}

export function SetupAdmin(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetupAdmin'](arg1, arg2, arg3, arg4);
}

export function TrimVideo(arg1) {
  return window['go']['main']['App']['TrimVideo'](arg1);
}

export function TrimVideoFast(arg1) {
  return window['go']['main']['App']['TrimVideoFast'](arg1);
}

export function UpdateAPIURL(arg1) {
  return window['go']['main']['App']['UpdateAPIURL'](arg1);
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}
