// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CleanupServe(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function ExtractThumbnail(arg1:string,arg2:number):Promise<string>;

export function FFmpegIsAvailable():Promise<boolean>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAuthStatus():Promise<main.AuthStatus>;

export function GetAuthToken():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetFileSize(arg1:string):Promise<number>;

export function GetMediaServerURL():Promise<string>;

export function HandleAuthCallback(arg1:string):Promise<Record<string, any>>;

export function InstallFFmpeg():Promise<void>;

export function IsDevMode():Promise<boolean>;

export function LoginAdmin(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LogoutDevice():Promise<void>;

export function OpenFileDialog():Promise<string>;

export function ProbeServer(arg1:string):Promise<main.AuthStatus>;

export function ProbeVideo(arg1:string):Promise<main.ProbeResult>;

export function ProxyVideoURL(arg1:string,arg2:string):Promise<string>;

export function RedeemInvite(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ServeLocalFile(arg1:string):Promise<string>;

export function SetupAdmin(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TrimVideo(arg1:main.TrimRequest):Promise<string>;

export function TrimVideoFast(arg1:main.TrimRequest):Promise<string>;

export function UpdateAPIURL(arg1:string):Promise<void>;

export function UploadFile(arg1:string):Promise<main.UploadResult>;
